version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: employee-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  webapp:
    image: employee-webapp:latest   # ‚≠ê ADD THIS
    build: .
    container_name: employee-webapp
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
